#include <iostream>
#include <string>
using namespace std;

void magicBall(string questions) {//the function is declared as a void since it won't be returning a value. It also has a string variable declared.
	string magicAnswers[20] =//this one is going to be quite long. 20 string values means a lot of writing.
	{ "It is certain.", "Without a doubt.", "You must rely on it.", "Yes. Definetely.", "It is decideedly so.", "As I see it. Yes.", "Most Likely.", "Yes.", "Outlook good.", "Signs point to yes.", "Reply hazy, try again.", "Better not tell you now.", "Ask again later.", "Cannot predict now.", "Concentrate and ask again.", "Don't count on it.", "Outlook not so good.", "My sources say no.", "Very doubtful.", "No." };
	//it is done. These are all the answers that will be given to the user after their question.
	srand(time(NULL));//this creates a seed for the random variable.
	int random = rand() % 20 + 1;//this generates a random number up to 20.
	for (int i = 0; i < 20; i++) {//a for loop to loop through the array of strings.
		if (i == random) {//if the number from the loop is the same as the number generated by the rng.
			cout << "A: " << magicAnswers[i];//outputs one of the strings depending on the number to the console.
		}
	}
}

void logMessage(string mesg) {//this makes it easier to write messages for the console.
	cout << mesg << endl;
}

int main() {
	string userQuestion;//a string variable for the user input.
	logMessage("Please enter your question...");//this is printed to the console.
	cout << "Q: ";//this is also printed to the console. Because I don't want it to skip a line for the input, it is not in the logMessage function.
	getline(cin,userQuestion);//getline and cin for the user input.
	magicBall(userQuestion);//the string is then sent over to the function.

	return 0;
}

//8 ball answers taken from this webpage: https://www.taurusandscorpio.net/list-of-magic-8-ball-responses/
